apiVersion: v1
kind: Pod
metadata:
  name: zookeeper
spec:
  containers:
    - image: stackable/zookeeper:3.6.2
      imagePullPolicy: Always
      name: greet
  tolerations:
    - key: "node.kubernetes.io/network-unavailable"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "kubernetes.io/arch"
      operator: "Equal"
      value: "stackable-linux"
      effect: "NoExecute"
    - key: "kubernetes.io/arch"
      operator: "Equal"
      value: "stackable-linux"
      effect: "NoSchedule"
